# Generated by Django 3.0.3 on 2020-02-13 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pam',
            fields=[
                ('id_Pt', models.IntegerField(primary_key=True, serialize=False)),
                ('Nom_scientifique', models.CharField(max_length=100)),
                ('nom_vulgaire', models.CharField(max_length=100)),
                ('ordre', models.CharField(max_length=100)),
                ('famille', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('multiplication', models.CharField(max_length=100)),
                ('inflorescence', models.CharField(max_length=100)),
                ('type_biologique', models.CharField(max_length=100)),
                ('climat', models.CharField(max_length=100)),
                ('sol', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Utilite',
            fields=[
                ('id_Utilite', models.IntegerField(primary_key=True, serialize=False)),
                ('maladie', models.CharField(max_length=100)),
                ('mode_emploi', models.CharField(max_length=100)),
                ('pamss', models.ManyToManyField(to='Caracteristqiue.Pam', verbose_name='Avoir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pam',
            name='utilitess',
            field=models.ManyToManyField(to='Caracteristqiue.Utilite', verbose_name='Avoir'),
        ),
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caracteristqiue.Pam')),
                ('utilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caracteristqiue.Utilite')),
            ],
        ),
    ]
