# Generated by Django 3.0.3 on 2020-02-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caracteristqiue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pam',
            name='slug',
            field=models.SlugField(default='simo', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
